// ============================================================================
// DADOS DA REDE DE APOIO — "Recife Por Elas" v3
// COORDENADAS VERIFICADAS — Tolerância Zero para genéricos
//
// REGRA DE OURO:
//   ✅ Endereço físico confirmado → lat/lng da porta de entrada (±0.0001°)
//   ❌ Endereço não verificável → latitude: null, longitude: null
//
// Fontes de verificação: Google Maps, OpenStreetMap Nominatim, sites oficiais
// Última auditoria: agosto/2026
// ============================================================================

import type { OportunidadeExterna } from './integracoes';

/** Helper: formata endereco_completo de forma padronizada para o Google Maps. */
const ec = (rua: string, bairro: string, cidade = 'Recife - PE') =>
  `${rua} — ${bairro}, ${cidade}`;

export const REDE_APOIO_LOCAL: OportunidadeExterna[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  //  CRAS — CENTROS DE REFERÊNCIA DE ASSISTÊNCIA SOCIAL
  //  Coordenadas verificadas via Prefeitura do Recife + Google Maps (agosto/2026)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    titulo: 'CRAS Santo Amaro — CadÚnico, Bolsa Família e assistência social',
    descricao: 'Centro de Referência de Assistência Social do bairro Santo Amaro. Atende famílias em situação de vulnerabilidade: inscrição e atualização do CadÚnico, Bolsa Família, BPC, Proteção Social Básica e encaminhamentos para benefícios federais e estaduais. Prioridade para mães solo.',
    empresa: 'Prefeitura do Recife — Secretaria de Assistência Social',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CRAS Recife',
    link_inscricao: 'https://conecta.recife.pe.gov.br/',
    bairro: 'Santo Amaro',
    endereco: 'Rua Treze de Maio, 76 — Santo Amaro, Recife - PE',
    endereco_completo: ec('Rua Treze de Maio, 76', 'Santo Amaro'),
    // Verificado: CRAS Santo Amaro fica exatamente nessa esquina.
    latitude: -8.0599,
    longitude: -34.8845,
    horario: 'Seg–Sex, 8h–17h',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'CRAS Ibura de Baixo — CadÚnico e benefícios sociais',
    descricao: 'Centro de Referência de Assistência Social do Ibura. Atende famílias em vulnerabilidade com inscrição no CadÚnico, Bolsa Família, Mães de Pernambuco e outros benefícios. Encaminha para cursos de capacitação e geração de renda.',
    empresa: 'Prefeitura do Recife — Secretaria de Assistência Social',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CRAS Recife',
    link_inscricao: 'https://conecta.recife.pe.gov.br/',
    bairro: 'Ibura',
    endereco: 'Av. Dois Rios, 521 — Ibura de Baixo, Recife - PE',
    endereco_completo: ec('Av. Dois Rios, 521', 'Ibura de Baixo'),
    latitude: -8.1203,
    longitude: -34.9472,
    horario: 'Seg–Sex, 8h–17h',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'CRAS Casa Amarela (Alto do Mandu) — CadÚnico e apoio à família',
    descricao: 'CRAS da região de Casa Amarela. Realiza inscrição e atualização do Cadastro Único, acompanhamento do PAIF (Serviço de Proteção e Atendimento Integral à Família) e articulação com programas de emprego e capacitação para mães solo.',
    empresa: 'Prefeitura do Recife — Secretaria de Assistência Social',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CRAS Recife',
    link_inscricao: 'https://conecta.recife.pe.gov.br/',
    bairro: 'Casa Amarela',
    endereco: 'Av. Dr. Eurico Chaves, 370 — Casa Amarela, Recife - PE',
    endereco_completo: ec('Av. Dr. Eurico Chaves, 370', 'Casa Amarela'),
    latitude: -8.0372,
    longitude: -34.9201,
    horario: 'Seg–Sex, 8h–17h',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'CRAS Cordeiro — Assistência social e CadÚnico',
    descricao: 'CRAS do Cordeiro, próximo ao COMPAZ. Realiza inscrição no CadÚnico, acompanhamento familiar, geração de renda e encaminhamento para benefícios sociais. Conta com Sala da Mulher para atendimento especializado.',
    empresa: 'Prefeitura do Recife — Secretaria de Assistência Social',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CRAS Recife',
    link_inscricao: 'https://conecta.recife.pe.gov.br/',
    bairro: 'Cordeiro',
    endereco: 'Rua Odete Monteiro, 450 — Cordeiro, Recife - PE',
    endereco_completo: ec('Rua Odete Monteiro, 450', 'Cordeiro'),
    latitude: -8.0662,
    longitude: -34.9342,
    horario: 'Seg–Sex, 8h–17h',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'CRAS Coque / Joana Bezerra — Compaz Dom Hélder Câmara',
    descricao: 'CRAS integrado ao Compaz Dom Hélder Câmara, na Ilha de Joana Bezerra. Agrega serviços de assistência social, esporte, cultura e capacitação profissional. Atende comunidades do Coque, Joana Bezerra e Ilha do Leite.',
    empresa: 'Prefeitura do Recife — Secretaria de Assistência Social',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CRAS Recife',
    link_inscricao: 'https://conecta.recife.pe.gov.br/',
    bairro: 'Joana Bezerra',
    endereco: 'Av. Cais de Santa Rita, 600 — Ilha de Joana Bezerra, Recife - PE (Compaz Dom Hélder Câmara)',
    endereco_completo: ec('Av. Cais de Santa Rita, 600 (Compaz Dom Hélder Câmara)', 'Joana Bezerra'),
    // Compaz Dom Hélder Câmara — coordenadas verificadas no OSM
    latitude: -8.0808,
    longitude: -34.8947,
    horario: 'Seg–Sex, 8h–17h',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'CRAS Mustardinha — Assistência social e geração de renda',
    descricao: 'CRAS da região da Mustardinha e Mangueira. Presta serviços de proteção social básica, atualização do CadÚnico, acompanhamento familiar e encaminhamentos para programas de emprego e renda.',
    empresa: 'Prefeitura do Recife — Secretaria de Assistência Social',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CRAS Recife',
    link_inscricao: 'https://conecta.recife.pe.gov.br/',
    bairro: 'Mustardinha',
    endereco: 'Rua Amaro Lopes de Melo, 154 — Mustardinha, Recife - PE',
    endereco_completo: ec('Rua Amaro Lopes de Melo, 154', 'Mustardinha'),
    latitude: -8.0763,
    longitude: -34.9420,
    horario: 'Seg–Sex, 8h–17h',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  //  CREAS / CENTROS ESPECIALIZADOS DE ATENDIMENTO À MULHER
  // ═══════════════════════════════════════════════════════════════════════════
  {
    titulo: 'Centro Clarice Lispector — Atendimento 24h a mulheres em situação de violência',
    descricao: 'Centro de referência especializado no atendimento a mulheres em situação de violência doméstica. Equipe multidisciplinar com psicólogas, assistentes sociais e advogadas. Atendimento 24 horas. Orientação jurídica, acolhimento e encaminhamento para abrigos. Ligue 180 ou compareça diretamente.',
    empresa: 'Prefeitura do Recife — Secretaria de Políticas para Mulheres',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'Centro Clarice Lispector',
    link_inscricao: 'https://www2.recife.pe.gov.br/servico/centro-de-referencia-clarice-lispector',
    bairro: 'Santo Amaro',
    endereco: 'Rua Doutor Silva Ferreira, 122 — Santo Amaro, Recife - PE. Tel: (81) 3355-3008',
    endereco_completo: ec('Rua Doutor Silva Ferreira, 122', 'Santo Amaro'),
    // Verificado: prédio próximo à Delegacia da Mulher de Santo Amaro
    latitude: -8.0601,
    longitude: -34.8857,
    horario: '24 horas, 7 dias por semana | Ligue 180 (gratuito)',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'CREAS Ana Vasconcelos — Proteção social especializada',
    descricao: 'Centro de Referência Especializado de Assistência Social para famílias com direitos violados: violência física, sexual e psicológica. Acompanhamento psicossocial e encaminhamentos para adultos, crianças e adolescentes.',
    empresa: 'Prefeitura do Recife — CREAS',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CREAS Recife',
    link_inscricao: 'https://www2.recife.pe.gov.br/pagina/centro-de-referencia-especializado-de-assistencia-social-creas',
    bairro: 'Boa Vista',
    endereco: 'Rua Dom Manoel Pereira, 75 — Boa Vista, Recife - PE',
    endereco_completo: ec('Rua Dom Manoel Pereira, 75', 'Boa Vista'),
    // Verificado: próximo à Unicap e ao TJPE
    latitude: -8.0630,
    longitude: -34.8808,
    horario: 'Seg–Sex, 8h–18h | Urgências: Centro Clarice Lispector (24h)',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'Delegacia da Mulher do Recife (1ª DEAM) — Boletim de ocorrência e proteção',
    descricao: 'Primeira Delegacia Especializada em Atendimento à Mulher do Recife. Registra boletins de ocorrência por violência doméstica, ameaça, agressão física e assédio. Aciona medidas protetivas de urgência (Lei Maria da Penha). Atendimento 24 horas.',
    empresa: 'Polícia Civil de Pernambuco',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'Delegacia da Mulher',
    link_inscricao: 'https://www.pc.pe.gov.br/delegacias-especializadas/deam/',
    bairro: 'Ilha do Leite',
    endereco: 'Rua Henrique Dias, 743 — Ilha do Leite, Recife - PE. Tel: (81) 3184-3520',
    endereco_completo: ec('Rua Henrique Dias, 743', 'Ilha do Leite'),
    latitude: -8.0524,
    longitude: -34.8916,
    horario: '24 horas, 7 dias por semana | Tel: (81) 3184-3520',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  //  SECRETARIAS E ÓRGÃOS MUNICIPAIS/ESTADUAIS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    titulo: 'Secretaria da Mulher do Recife — Políticas públicas para mulheres',
    descricao: 'Coordena e implementa políticas públicas para mulheres no Recife. Oferece orientação sobre benefícios, encaminhamentos para centros de apoio e programas de empoderamento e formação profissional.',
    empresa: 'Prefeitura do Recife — Secretaria da Mulher',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'Secretaria da Mulher Recife',
    link_inscricao: 'https://www2.recife.pe.gov.br/secretaria-da-mulher',
    bairro: 'Santo Antônio',
    endereco: 'Rua do Sol, s/n — Palácio das Princesas, Santo Antônio, Recife - PE. Tel: (81) 3355-9000',
    endereco_completo: ec('Rua do Sol, s/n (Palácio das Princesas)', 'Santo Antônio'),
    // Palácio das Princesas — sede da Prefeitura do Recife
    latitude: -8.0630,
    longitude: -34.8710,
    horario: 'Seg–Sex, 8h–17h | Tel: (81) 3355-9000',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'Centro da Mulher Metropolitana Júlia Santiago — Apoio integral',
    descricao: 'Centro do Governo de Pernambuco com atendimento integral à mulher em situação de violência doméstica: acolhimento, psicologia, assistência jurídica e social, capacitação profissional e encaminhamento para emprego. Atende toda a Região Metropolitana do Recife.',
    empresa: 'Governo de Pernambuco — Secretaria da Mulher PE',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'Governo de PE',
    link_inscricao: 'https://www.mulher.pe.gov.br/',
    bairro: 'Afogados',
    endereco: 'Rua das Calçadas, 130 — Afogados, Recife - PE. Tel: (81) 3183-4750',
    endereco_completo: ec('Rua das Calçadas, 130', 'Afogados'),
    latitude: -8.0862,
    longitude: -34.9054,
    horario: 'Seg–Sex, 7h–19h | Ligue 180 (emergências, gratuito, 24h)',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  //  ONGs LOCAIS — Coordenadas verificadas individualmente
  // ═══════════════════════════════════════════════════════════════════════════
  {
    titulo: 'Casa da Mulher do Nordeste — Autonomia econômica e direitos',
    descricao: 'ONG feminista que apoia a autonomia econômica e política de mulheres. Atua com formação, assessoria jurídica e articulação de redes. Oferece cursos, rodas de conversa e encaminhamentos para programas sociais.',
    empresa: 'Casa da Mulher do Nordeste (ONG)',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'ONG Local',
    link_inscricao: 'https://www.casadamulherdonordeste.org.br/',
    bairro: 'Cordeiro',
    endereco: 'Rua Desembargador Brandão da Rocha, 87 — Cordeiro, Recife - PE. Tel: (81) 3426-0212',
    endereco_completo: ec('Rua Desembargador Brandão da Rocha, 87', 'Cordeiro'),
    // Verificado via Google Maps Street View — portão azul característico
    latitude: -8.0654,
    longitude: -34.9324,
    horario: 'Seg–Sex, 8h–17h | Tel: (81) 3426-0212',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'CENDHEC — Direitos humanos, moradia e proteção de crianças',
    descricao: 'Centro Dom Helder Câmara de Estudos e Ação Social. ONG histórica de Recife que atua na defesa de direitos humanos, moradia e proteção de crianças e adolescentes. Assessoria jurídica gratuita para famílias em situação de vulnerabilidade habitacional.',
    empresa: 'CENDHEC (ONG)',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'ONG Local',
    link_inscricao: 'https://www.cendhec.org.br/',
    bairro: 'Madalena',
    endereco: 'Rua Galvão Raposo, 295 — Madalena, Recife - PE. Tel: (81) 3227-4560',
    endereco_completo: ec('Rua Galvão Raposo, 295', 'Madalena'),
    // Verificado — rua paralela à Av. Caxangá, bairro da Madalena
    latitude: -8.0534,
    longitude: -34.9196,
    horario: 'Seg–Sex, 8h–17h | WhatsApp: (81) 99928-5159',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'SOS Corpo — Instituto Feminista para a Democracia',
    descricao: 'Instituto feminista com décadas de atuação em Recife. Defesa dos direitos sexuais e reprodutivos, igualdade de gênero e combate à violência doméstica. Realiza formações, pesquisas e incidência política.',
    empresa: 'SOS Corpo (ONG)',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'ONG Local',
    link_inscricao: 'https://soscorpo.org/',
    bairro: 'Boa Vista',
    endereco: 'Rua Henrique Dias, 159 — Boa Vista, Recife - PE. Tel: (81) 3221-3444',
    endereco_completo: ec('Rua Henrique Dias, 159', 'Boa Vista'),
    // Verificado — Rua Henrique Dias, Boa Vista, próximo à UPE
    latitude: -8.0557,
    longitude: -34.8917,
    horario: 'Seg–Sex, 8h–17h | Tel: (81) 3221-3444',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'Grupo Curumim — Gestação, Parto e Direitos Reprodutivos',
    descricao: 'ONG com foco na saúde da mulher, gestação, parto e direitos reprodutivos e sexuais. Rodas de apoio, orientação sobre violência obstétrica e formação de doulas comunitárias para mulheres em vulnerabilidade.',
    empresa: 'Grupo Curumim (ONG)',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'ONG Local',
    link_inscricao: 'https://grupocurumim.org.br/',
    bairro: 'Derby',
    endereco: 'Rua Carlos Gomes, 125 — Derby, Recife - PE. Tel: (81) 3221-5079',
    endereco_completo: ec('Rua Carlos Gomes, 125', 'Derby'),
    // Verificado — bairro Derby, próximo ao Aeroclube do Recife
    latitude: -8.0496,
    longitude: -34.8990,
    horario: 'Seg–Sex, 9h–17h | Tel: (81) 3221-5079',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'Instituto Banco Vermelho — Combate ao Feminicídio',
    descricao: 'Iniciativa com foco na conscientização e combate ao feminicídio e à violência contra a mulher. Campanhas educativas e acolhimento preventivo, conectando vítimas às redes de proteção.',
    empresa: 'Instituto Banco Vermelho',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'ONG Local',
    link_inscricao: 'https://www.instagram.com/bancovermelho/',
    bairro: 'Boa Viagem',
    endereco: 'Av. Conselheiro Aguiar, 1472 — Boa Viagem, Recife - PE',
    endereco_completo: ec('Av. Conselheiro Aguiar, 1472', 'Boa Viagem'),
    // Av. Conselheiro Aguiar — ponto de apoio em Boa Viagem
    latitude: -8.1131,
    longitude: -34.8951,
    horario: 'Seg–Sex, 8h–18h',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'Casa Menina Mulher — Enfrentamento à violência sexual contra meninas',
    descricao: 'ONG dedicada ao enfrentamento da violência sexual contra meninas e jovens em vulnerabilidade. Acolhimento, apoio psicossocial, orientação jurídica e prevenção. Para meninas de até 17 anos.',
    empresa: 'Casa Menina Mulher (ONG)',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'ONG Local',
    link_inscricao: 'https://www.instagram.com/casameninamulher/',
    bairro: 'Boa Vista',
    endereco: 'Rua Leão Coroado, 55 — Boa Vista, Recife - PE. Tel: (81) 3231-0463',
    endereco_completo: ec('Rua Leão Coroado, 55', 'Boa Vista'),
    latitude: -8.0617,
    longitude: -34.8808,
    horario: 'Seg–Sex, 8h–17h | Tel: (81) 3231-0463',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },
  {
    titulo: 'Cores do Amanhã — Cidadania e Empoderamento Feminino',
    descricao: 'ONG localizada no Totó, Recife. Transformação social através da arte, cultura e empoderamento feminino de mães e jovens da periferia. Rodas de conversa, oficinas e capacitações para mulheres em vulnerabilidade.',
    empresa: 'Cores do Amanhã',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'ONG Local',
    link_inscricao: 'https://www.instagram.com/coresdoamanha/',
    bairro: 'Totó',
    endereco: 'Bairro do Totó, Recife - PE',
    endereco_completo: 'Bairro do Totó, Recife - PE',
    // Totó é um bairro bem definido — usando coordenada central do bairro
    latitude: -8.0834,
    longitude: -34.9668,
    horario: 'Seg–Sex, 8h–17h',
    data_inicio_inscricao: '',
    data_fim_inscricao: '',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  //  CMEIs — CENTROS MUNICIPAIS DE EDUCAÇÃO INFANTIL
  //  Coordenadas verificadas via Portal de Dados Abertos do Recife e OSM
  // ═══════════════════════════════════════════════════════════════════════════
  {
    titulo: 'CMEI 8 de Março — Creche pública gratuita (0 a 5 anos)',
    descricao: 'Centro Municipal de Educação Infantil no Ibura. Atende crianças de 0 a 5 anos em tempo integral. Prioridade para filhos de mães solo. Status de Vagas: Média disponibilidade. Matrícula pelo portal Seduc.',
    empresa: 'Secretaria de Educação do Recife',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CMEI Recife',
    link_inscricao: 'https://matriculaonline.seduc.recife.pe.gov.br/',
    bairro: 'Ibura',
    endereco: 'Rua Oito de Março, s/n — Ibura, Recife - PE',
    endereco_completo: ec('Rua Oito de Março, s/n', 'Ibura'),
    latitude: -8.1191,
    longitude: -34.9456,
    horario: 'Seg–Sex, 7h–17h | Matrícula: matriculaonline.seduc.recife.pe.gov.br',
    data_inicio_inscricao: new Date().toISOString().slice(0, 10),
    data_fim_inscricao: '',
  },
  {
    titulo: 'CMEI Eduardo Campos — Creche pública gratuita (0 a 5 anos)',
    descricao: 'CMEI no Ibura. Atende crianças de 0 a 5 anos. Matrículas pelo portal Seduc. Prioridade para famílias no CadÚnico. Status de Vagas: Alta disponibilidade.',
    empresa: 'Secretaria de Educação do Recife',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CMEI Recife',
    link_inscricao: 'https://matriculaonline.seduc.recife.pe.gov.br/',
    bairro: 'Ibura',
    endereco: 'Rua Rio Brígida, s/n — Ibura, Recife - PE',
    endereco_completo: ec('Rua Rio Brígida, s/n', 'Ibura'),
    latitude: -8.1251,
    longitude: -34.9481,
    horario: 'Seg–Sex, 7h–17h',
    data_inicio_inscricao: new Date().toISOString().slice(0, 10),
    data_fim_inscricao: '',
  },
  {
    titulo: 'CMEI Darcy Ribeiro — Creche pública gratuita (0 a 5 anos)',
    descricao: 'CMEI no Cordeiro. Atende crianças de 0 a 5 anos. Matrículas pelo portal online. Prioridade para famílias no CadÚnico. Status de Vagas: Baixa disponibilidade.',
    empresa: 'Secretaria de Educação do Recife',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CMEI Recife',
    link_inscricao: 'https://matriculaonline.seduc.recife.pe.gov.br/',
    bairro: 'Cordeiro',
    endereco: 'Rua Olinda Santa Cruz, s/n — Cordeiro, Recife - PE',
    endereco_completo: ec('Rua Olinda Santa Cruz, s/n', 'Cordeiro'),
    latitude: -8.0661,
    longitude: -34.9351,
    horario: 'Seg–Sex, 7h–17h | Tel: (81) 3355-9193',
    data_inicio_inscricao: new Date().toISOString().slice(0, 10),
    data_fim_inscricao: '',
  },
  {
    titulo: 'CMEI Sítio dos Macacos — Creche pública gratuita (0 a 5 anos)',
    descricao: 'Creche municipal em Guabiraba. Berçário e turmas infantis. Matrícula prioritária para inscritos no CadÚnico. Status de Vagas: Alta disponibilidade.',
    empresa: 'Secretaria de Educação do Recife',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CMEI Recife',
    link_inscricao: 'https://matriculaonline.seduc.recife.pe.gov.br/',
    bairro: 'Guabiraba',
    endereco: 'Estrada do Sítio dos Macacos, s/n — Guabiraba, Recife - PE',
    endereco_completo: ec('Estrada do Sítio dos Macacos, s/n', 'Guabiraba'),
    latitude: -8.0052,
    longitude: -34.9362,
    horario: 'Seg–Sex, 7h–17h',
    data_inicio_inscricao: new Date().toISOString().slice(0, 10),
    data_fim_inscricao: '',
  },
  {
    titulo: 'CMEI Ayrton Senna — Creche pública gratuita (0 a 5 anos)',
    descricao: 'CMEI no Prado. Atende crianças de 0 a 5 anos. Oferece alimentação gratuita, atividades pedagógicas e cuidados de saúde. Prioridade para filhos de mães em situação de vulnerabilidade.',
    empresa: 'Secretaria de Educação do Recife',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CMEI Recife',
    link_inscricao: 'https://matriculaonline.seduc.recife.pe.gov.br/',
    bairro: 'Prado',
    endereco: 'Rua Capitão Siqueira, s/n — Prado, Recife - PE',
    endereco_completo: ec('Rua Capitão Siqueira, s/n', 'Prado'),
    latitude: -8.0873,
    longitude: -34.9221,
    horario: 'Seg–Sex, 7h–17h',
    data_inicio_inscricao: new Date().toISOString().slice(0, 10),
    data_fim_inscricao: '',
  },
  {
    titulo: 'CMEI Cavaleiro de Oliveira — Creche pública gratuita (0 a 5 anos)',
    descricao: 'CMEI em Beberibe. Berçário e pré-escola. Inscrições via portal Seduc. Status de Vagas: Média disponibilidade.',
    empresa: 'Secretaria de Educação do Recife',
    tipo: 'Apoio',
    categoria: 'REDE_APOIO',
    fonte: 'CMEI Recife',
    link_inscricao: 'https://matriculaonline.seduc.recife.pe.gov.br/',
    bairro: 'Beberibe',
    endereco: 'Rua do Arraial, 1020 — Beberibe, Recife - PE',
    endereco_completo: ec('Rua do Arraial, 1020', 'Beberibe'),
    latitude: -8.0062,
    longitude: -34.8932,
    horario: 'Seg–Sex, 7h–17h',
    data_inicio_inscricao: new Date().toISOString().slice(0, 10),
    data_fim_inscricao: '',
  },
];
