name: Deploy na Oracle Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executar Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 163.176.158.165
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd ~/recife-por-elas
            git pull origin main
            docker compose up -d --build
